**Applied Data Science with Python Specialization (Coursera)**
#### **Course 1: Introduction to Data Science in Python (C1)**

## **(Week 2) - (2) DataFrame**

###**a. Data Structure**

In [2]:
import pandas as pd

In [ ]:
record1=pd.Series({'Name':'Alice',
                   'Class':'Physics',
                   'Score':85})
record2=pd.Series({'Name':'Jack',
                   'Class':'Chemistry',
                   'Score':82})
record3=pd.Series({'Name':'Helen',
                   'Class':'Biology',
                   'Score':90})

In [ ]:
df=pd.DataFrame([record1,record2,record3],index=['school1','school2','school1'])
df #Or you can also use df.head() which in default will show the top 5 of the DF

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [ ]:
#Alternative method is using dictonaries
students=[{'Name':'Alice',
           'Class':'Physics',
           'Score':85},
          {'Name':'Jack',
           'Class':'Chemistry',
           'Score':82},
          {'Name':'Helen',
           'Class':'Biology',
           'Score':90}]

In [ ]:
df=pd.DataFrame([record1,record2,record3],index=['school1','school2','school1'])
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [ ]:
#Trying the loc function
df.loc['school2']

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [ ]:
#Checking the data type
type(df.loc['school2'])

pandas.core.series.Series

In [ ]:
df.loc['school1']

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [ ]:
type(df.loc['school1'])

pandas.core.frame.DataFrame

In [ ]:
df.loc['school1','Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [ ]:
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [ ]:
#Transposing DataFrame
dftransposed=df.T
dftransposed

       school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

In [ ]:
#Use transpose funtion for loc
df.T.loc['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [ ]:
dftransposed.T.loc['school1']

          Name    Class Score
school1  Alice  Physics    85
school1  Helen  Biology    90

In [ ]:
dftransposed.loc['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [ ]:
#NOTE: the result of a single column projection is a Series object
type(df['Name'])

pandas.core.series.Series

In [ ]:
df.loc['school1']['Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [ ]:
print(type(df.loc['school1']))
print(type(df.loc['school1']['Name']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [ ]:
df.loc[:,['Name','Score']]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

In [ ]:
df.drop('school1')

         Name      Class  Score
school2  Jack  Chemistry     82

In [ ]:
copy_df=df.copy()

In [ ]:
copy_df.drop("Name",inplace=True,axis=1)
copy_df

             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [ ]:
del copy_df['Class']
copy_df

         Score
school1     85
school2     82
school1     90

In [ ]:
df['ClassRanking']=None
df

          Name      Class  Score ClassRanking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     90         None

###**b. Indexing and Loading**

In [3]:
df=pd.read_csv("/content/Admission_Predict.csv")
df

     Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0             1        337          118  ...  9.65         1              0.92
1             2        324          107  ...  8.87         1              0.76
2             3        316          104  ...  8.00         1              0.72
3             4        322          110  ...  8.67         1              0.80
4             5        314          103  ...  8.21         0              0.65
..          ...        ...          ...  ...   ...       ...               ...
395         396        324          110  ...  9.04         1              0.82
396         397        325          107  ...  9.11         1              0.84
397         398        330          116  ...  9.45         1              0.91
398         399        312          103  ...  8.78         0              0.67
399         400        333          117  ...  9.66         1              0.95

[400 rows x 9 columns]

In [4]:
#Change the Index using the "Serial No." Column
df=pd.read_csv("/content/Admission_Predict.csv",
               index_col=0)
df

            GRE Score  TOEFL Score  ...  Research  Chance of Admit
Serial No.                          ...
1                 337          118  ...         1              0.92
2                 324          107  ...         1              0.76
3                 316          104  ...         1              0.72
4                 322          110  ...         1              0.80
5                 314          103  ...         0              0.65
...               ...          ...  ...       ...               ...
396               324          110  ...         1              0.82
397               325          107  ...         1              0.84
398               330          116  ...         1              0.91
399               312          103  ...         0              0.67
400               333          117  ...         1              0.95

[400 rows x 8 columns]

In [6]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [7]:
#Renaming the Column Names
new_df=df.rename(columns={'GRE Score':'GRE Score',
                          'TOEFL Score':'TOEFL Score',
                          'University Rating':'University Rating',
                          'SOP':'Statement of Purpose',
                          'LOR ':'Letter of Recommendation',
                          'CGPA':'CGPA',
                          'Research':'Research',
                          'Chance of Admit':'Chance of Admit'})
new_df.sample(10)

            GRE Score  TOEFL Score  ...  Research  Chance of Admit
Serial No.                          ...
44                332          117  ...         0              0.87
316               308          104  ...         0              0.65
397               325          107  ...         1              0.84
142               332          118  ...         1              0.90
103               314          106  ...         0              0.62
13                328          112  ...         1              0.78
254               335          115  ...         1              0.93
358               301          104  ...         1              0.68
87                315          106  ...         0              0.72
180               307          102  ...         0              0.73

[10 rows x 8 columns]

In [ ]:
#Another way to rename
#other_df=new_df.rename(mapper=str.strip,axis='columns')

In [8]:
#Change all column names to lowercases
cols=list(df.columns)
cols=[x.lower().strip() for x in cols]

df.columns=cols
df

            gre score  toefl score  ...  research  chance of admit
Serial No.                          ...
1                 337          118  ...         1             0.92
2                 324          107  ...         1             0.76
3                 316          104  ...         1             0.72
4                 322          110  ...         1             0.80
5                 314          103  ...         0             0.65
...               ...          ...  ...       ...              ...
396               324          110  ...         1             0.82
397               325          107  ...         1             0.84
398               330          116  ...         1             0.91
399               312          103  ...         0             0.67
400               333          117  ...         1             0.95

[400 rows x 8 columns]

###**c. Querying**

In [9]:
admit_mask=df['chance of admit']>0.7
admit_mask

Serial No.
1       True
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398     True
399    False
400     True
Name: chance of admit, Length: 400, dtype: bool

In [10]:
df.where(admit_mask).head(10)

            gre score  toefl score  ...  research  chance of admit
Serial No.                          ...
1               337.0        118.0  ...       1.0             0.92
2               324.0        107.0  ...       1.0             0.76
3               316.0        104.0  ...       1.0             0.72
4               322.0        110.0  ...       1.0             0.80
5                 NaN          NaN  ...       NaN              NaN
6               330.0        115.0  ...       1.0             0.90
7               321.0        109.0  ...       1.0             0.75
8                 NaN          NaN  ...       NaN              NaN
9                 NaN          NaN  ...       NaN              NaN
10                NaN          NaN  ...       NaN              NaN

[10 rows x 8 columns]

In [11]:
df.where(admit_mask).dropna().head(10)

            gre score  toefl score  ...  research  chance of admit
Serial No.                          ...
1               337.0        118.0  ...       1.0             0.92
2               324.0        107.0  ...       1.0             0.76
3               316.0        104.0  ...       1.0             0.72
4               322.0        110.0  ...       1.0             0.80
6               330.0        115.0  ...       1.0             0.90
7               321.0        109.0  ...       1.0             0.75
12              327.0        111.0  ...       1.0             0.84
13              328.0        112.0  ...       1.0             0.78
23              328.0        116.0  ...       1.0             0.94
24              334.0        119.0  ...       1.0             0.95

[10 rows x 8 columns]

In [13]:
df[df['chance of admit']>0.7].head(10)

            gre score  toefl score  ...  research  chance of admit
Serial No.                          ...
1                 337          118  ...         1             0.92
2                 324          107  ...         1             0.76
3                 316          104  ...         1             0.72
4                 322          110  ...         1             0.80
6                 330          115  ...         1             0.90
7                 321          109  ...         1             0.75
12                327          111  ...         1             0.84
13                328          112  ...         1             0.78
23                328          116  ...         1             0.94
24                334          119  ...         1             0.95

[10 rows x 8 columns]

In [14]:
df["gre score"].head()

Serial No.
1    337
2    324
3    316
4    322
5    314
Name: gre score, dtype: int64

In [16]:
df[df["gre score"]>320].head(10)

            gre score  toefl score  ...  research  chance of admit
Serial No.                          ...
1                 337          118  ...         1             0.92
2                 324          107  ...         1             0.76
4                 322          110  ...         1             0.80
6                 330          115  ...         1             0.90
7                 321          109  ...         1             0.75
10                323          108  ...         0             0.45
11                325          106  ...         1             0.52
12                327          111  ...         1             0.84
13                328          112  ...         1             0.78
22                325          114  ...         0             0.70

[10 rows x 8 columns]

In [17]:
(df['chance of admit']>0.7) & (df['chance of admit']<0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [19]:
df['chance of admit'].gt(0.7) & df['chance of admit'].lt(0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [20]:
df['chance of admit'].gt(0.7).lt(0.9)

Serial No.
1      False
2      False
3      False
4      False
5       True
       ...
396    False
397    False
398    False
399     True
400    False
Name: chance of admit, Length: 400, dtype: bool

###**d. Indexing**

In [26]:
df=pd.read_csv("/content/Admission_Predict.csv",index_col=0)
df

            GRE Score  TOEFL Score  ...  Research  Chance of Admit
Serial No.                          ...
1                 337          118  ...         1              0.92
2                 324          107  ...         1              0.76
3                 316          104  ...         1              0.72
4                 322          110  ...         1              0.80
5                 314          103  ...         0              0.65
...               ...          ...  ...       ...               ...
396               324          110  ...         1              0.82
397               325          107  ...         1              0.84
398               330          116  ...         1              0.91
399               312          103  ...         0              0.67
400               333          117  ...         1              0.95

[400 rows x 8 columns]

In [27]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [28]:
#Setting the Index
df['Serial Number']=df.index

In [29]:
df=df.set_index('Chance of Admit ')
df.head()

                  GRE Score  TOEFL Score  ...  Research  Serial Number
Chance of Admit                           ...
0.92                    337          118  ...         1              1
0.76                    324          107  ...         1              2
0.72                    316          104  ...         1              3
0.80                    322          110  ...         1              4
0.65                    314          103  ...         0              5

[5 rows x 8 columns]

In [30]:
df=df.reset_index()
df.head()

   Chance of Admit   GRE Score  TOEFL Score  ...  CGPA  Research  Serial Number
0              0.92        337          118  ...  9.65         1              1
1              0.76        324          107  ...  8.87         1              2
2              0.72        316          104  ...  8.00         1              3
3              0.80        322          110  ...  8.67         1              4
4              0.65        314          103  ...  8.21         0              5

[5 rows x 9 columns]

In [31]:
df=pd.read_csv("/content/census.csv")
df

      SUMLEV  REGION  DIVISION  ...  RNETMIG2013  RNETMIG2014 RNETMIG2015
0         40       3         6  ...     1.383282     1.724718    0.712594
1         50       3         6  ...    -2.722002     2.592270   -2.187333
2         50       3         6  ...    22.727626    20.317142   18.293499
3         50       3         6  ...    -7.167664    -3.978583  -10.543299
4         50       3         6  ...    -5.403729     0.754533    1.107861
...      ...     ...       ...  ...          ...          ...         ...
3188      50       4         8  ...    -5.295460   -14.075283  -14.070195
3189      50       4         8  ...    21.160658    16.308671    1.520747
3190      50       4         8  ...    -7.521840   -14.740608  -12.606351
3191      50       4         8  ...    -2.250385   -18.020168    1.441961
3192      50       4         8  ...    12.372583     1.533635    6.935294

[3193 rows x 100 columns]

In [32]:
df['SUMLEV'].unique()

array([40, 50])

In [33]:
df=df[df['SUMLEV']==50]
df.head()

   SUMLEV  REGION  DIVISION  ...  RNETMIG2013  RNETMIG2014 RNETMIG2015
1      50       3         6  ...    -2.722002     2.592270   -2.187333
2      50       3         6  ...    22.727626    20.317142   18.293499
3      50       3         6  ...    -7.167664    -3.978583  -10.543299
4      50       3         6  ...    -5.403729     0.754533    1.107861
5      50       3         6  ...    -1.402476    -1.577232   -0.884411

[5 rows x 100 columns]

In [34]:
columns_to_keep=['STNAME','CTYNAME','BIRTHS2010','BIRTHS2011','BIRTHS2012','BIRTHS2013','BIRTHS2014',
                 'BIRTHS2015','POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013',
                 'POPESTIMATE2014','POPESTIMATE2015']
df=df[columns_to_keep]
df.head()

    STNAME         CTYNAME  ...  POPESTIMATE2014  POPESTIMATE2015
1  Alabama  Autauga County  ...            55290            55347
2  Alabama  Baldwin County  ...           199713           203709
3  Alabama  Barbour County  ...            26815            26489
4  Alabama     Bibb County  ...            22549            22583
5  Alabama   Blount County  ...            57658            57673

[5 rows x 14 columns]

In [35]:
df=df.set_index(['STNAME','CTYNAME'])
df.head()

                        BIRTHS2010  ...  POPESTIMATE2015
STNAME  CTYNAME                     ...
Alabama Autauga County         151  ...            55347
        Baldwin County         517  ...           203709
        Barbour County          70  ...            26489
        Bibb County             44  ...            22583
        Blount County          183  ...            57673

[5 rows x 12 columns]

In [36]:
df.loc['Michigan','Washtenaw County']

BIRTHS2010            977
BIRTHS2011           3826
BIRTHS2012           3780
BIRTHS2013           3662
BIRTHS2014           3683
BIRTHS2015           3709
POPESTIMATE2010    345563
POPESTIMATE2011    349048
POPESTIMATE2012    351213
POPESTIMATE2013    354289
POPESTIMATE2014    357029
POPESTIMATE2015    358880
Name: (Michigan, Washtenaw County), dtype: int64

In [37]:
df.loc[[('Michigan','Washtenaw County'),
        ('Michigan','Wayne County')]]

                           BIRTHS2010  ...  POPESTIMATE2015
STNAME   CTYNAME                       ...
Michigan Washtenaw County         977  ...           358880
         Wayne County            5918  ...          1759335

[2 rows x 12 columns]

####**e. Missing Values**

In [38]:
df=pd.read_csv("/content/class_grades.csv")
df

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
2        8       83.70     83.17      NaN     63.15  48.89
3        7         NaN       NaN    49.38    105.93  80.56
4        8       91.32     93.64    95.00    107.41  73.89
..     ...         ...       ...      ...       ...    ...
94       8         NaN    103.71    45.00     93.52  61.94
95       7         NaN     80.54    41.25     93.70  39.72
96       8       89.94    102.77    87.50     90.74  87.78
97       7       95.60     76.13    66.25     99.81  85.56
98       8       63.40     97.37    73.12     72.78  77.22

[99 rows x 6 columns]

In [41]:
df.isnull().sum()

Prefix        0
Assignment    7
Tutorial      3
Midterm       3
TakeHome      5
Final         3
dtype: int64

In [39]:
mask=df.isnull()
mask.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0   False       False     False    False     False  False
1   False       False     False    False     False  False
2   False       False     False     True     False  False
3   False        True      True    False     False  False
4   False       False     False    False     False  False
5   False       False     False    False     False  False
6   False       False     False    False     False  False
7   False       False     False    False      True  False
8   False       False     False    False     False  False
9   False       False     False    False     False  False

In [42]:
df.fillna(0,inplace=True)
df.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0       5       57.14     34.09    64.38     51.48  52.50
1       8       95.05    105.49    67.50     99.07  68.33
2       8       83.70     83.17     0.00     63.15  48.89
3       7        0.00      0.00    49.38    105.93  80.56
4       8       91.32     93.64    95.00    107.41  73.89
5       7       95.00     92.58    93.12     97.78  68.06
6       8       95.05    102.99    56.25     99.07  50.00
7       7       72.85     86.85    60.00      0.00  56.11
8       8       84.26     93.10    47.50     18.52  50.83
9       7       90.10     97.55    51.25     88.89  63.61

In [40]:
df.dropna().head(10)

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
4        8       91.32     93.64    95.00    107.41  73.89
5        7       95.00     92.58    93.12     97.78  68.06
6        8       95.05    102.99    56.25     99.07  50.00
8        8       84.26     93.10    47.50     18.52  50.83
9        7       90.10     97.55    51.25     88.89  63.61
10       7       80.44     90.20    75.00     91.48  39.72
12       8       97.16    103.71    72.50     93.52  63.33
13       7       91.28     83.53    81.25     99.81  92.22

In [43]:
df=pd.read_csv("/content/log.csv")
df

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN
20  1469974754     sue  advanced.html                 30    NaN     NaN
21  1469974824     sue  advanced.html                 31    NaN     NaN
22  1469974854     sue  advanced.html                 32    NaN     NaN
23  1469974924     sue  advanced.html                 33    NaN     NaN
24  1469977424     bob     intro.html                  1   True    10.0
25  1469977454     bob     intro.html                  1    NaN     NaN
26  1469977484     bob     intro.html                  1    NaN     NaN
27  1469977634     bob     intro.html                  1    NaN     NaN
28  1469977664     bob     intro.html                  1    NaN     NaN
29  1469974634  cheryl     intro.html                 12    NaN     NaN
30  1469974664  cheryl     intro.html                 13    NaN     NaN
31  1469977694     bob     intro.html                  1    NaN     NaN
32  1469977724     bob     intro.html                  1    NaN     NaN

In [44]:
df=df.set_index('time')
df=df.sort_index()
df.head(10)

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974454     sue  advanced.html                 24    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974554     sue  advanced.html                 26    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN

In [45]:
df=df.reset_index()
df=df.set_index(['time','user'])
df

                           video  playback position paused  volume
time       user
1469974424 cheryl     intro.html                  5  False    10.0
           sue     advanced.html                 23  False    10.0
1469974454 cheryl     intro.html                  6    NaN     NaN
           sue     advanced.html                 24    NaN     NaN
1469974484 cheryl     intro.html                  7    NaN     NaN
1469974514 cheryl     intro.html                  8    NaN     NaN
1469974524 sue     advanced.html                 25    NaN     NaN
1469974544 cheryl     intro.html                  9    NaN     NaN
1469974554 sue     advanced.html                 26    NaN     NaN
1469974574 cheryl     intro.html                 10    NaN     NaN
1469974604 cheryl     intro.html                 11    NaN     NaN
1469974624 sue     advanced.html                 27    NaN     NaN
1469974634 cheryl     intro.html                 12    NaN     NaN
1469974654 sue     advanced.html                 28    NaN     5.0
1469974664 cheryl     intro.html                 13    NaN     NaN
1469974694 cheryl     intro.html                 14    NaN     NaN
1469974724 cheryl     intro.html                 15    NaN     NaN
           sue     advanced.html                 29    NaN     NaN
1469974754 sue     advanced.html                 30    NaN     NaN
1469974824 sue     advanced.html                 31    NaN     NaN
1469974854 sue     advanced.html                 32    NaN     NaN
1469974924 sue     advanced.html                 33    NaN     NaN
1469977424 bob        intro.html                  1   True    10.0
1469977454 bob        intro.html                  1    NaN     NaN
1469977484 bob        intro.html                  1    NaN     NaN
1469977514 bob        intro.html                  1    NaN     NaN
1469977544 bob        intro.html                  1    NaN     NaN
1469977574 bob        intro.html                  1    NaN     NaN
1469977604 bob        intro.html                  1    NaN     NaN
1469977634 bob        intro.html                  1    NaN     NaN
1469977664 bob        intro.html                  1    NaN     NaN
1469977694 bob        intro.html                  1    NaN     NaN
1469977724 bob        intro.html                  1    NaN     NaN

In [47]:
df=df.fillna(method='ffill')
df

                           video  playback position  paused  volume
time       user
1469974424 cheryl     intro.html                  5   False    10.0
           sue     advanced.html                 23   False    10.0
1469974454 cheryl     intro.html                  6   False    10.0
           sue     advanced.html                 24   False    10.0
1469974484 cheryl     intro.html                  7   False    10.0
1469974514 cheryl     intro.html                  8   False    10.0
1469974524 sue     advanced.html                 25   False    10.0
1469974544 cheryl     intro.html                  9   False    10.0
1469974554 sue     advanced.html                 26   False    10.0
1469974574 cheryl     intro.html                 10   False    10.0
1469974604 cheryl     intro.html                 11   False    10.0
1469974624 sue     advanced.html                 27   False    10.0
1469974634 cheryl     intro.html                 12   False    10.0
1469974654 sue     advanced.html                 28   False     5.0
1469974664 cheryl     intro.html                 13   False     5.0
1469974694 cheryl     intro.html                 14   False     5.0
1469974724 cheryl     intro.html                 15   False     5.0
           sue     advanced.html                 29   False     5.0
1469974754 sue     advanced.html                 30   False     5.0
1469974824 sue     advanced.html                 31   False     5.0
1469974854 sue     advanced.html                 32   False     5.0
1469974924 sue     advanced.html                 33   False     5.0
1469977424 bob        intro.html                  1    True    10.0
1469977454 bob        intro.html                  1    True    10.0
1469977484 bob        intro.html                  1    True    10.0
1469977514 bob        intro.html                  1    True    10.0
1469977544 bob        intro.html                  1    True    10.0
1469977574 bob        intro.html                  1    True    10.0
1469977604 bob        intro.html                  1    True    10.0
1469977634 bob        intro.html                  1    True    10.0
1469977664 bob        intro.html                  1    True    10.0
1469977694 bob        intro.html                  1    True    10.0
1469977724 bob        intro.html                  1    True    10.0

In [48]:
#Customized Fill-In
df=pd.DataFrame({'A':[1,1,2,3,4],
                 'B':[3,6,3,8,9],
                 'C':['a','b','c','d','e']})
df

   A  B  C
0  1  3  a
1  1  6  b
2  2  3  c
3  3  8  d
4  4  9  e

In [54]:
df.replace(1,"One")

     A  B  C
0  One  3  a
1  One  6  b
2    2  3  c
3    3  8  d
4    4  9  e

In [56]:
df.replace([1,3],["One","Three"])

       A      B  C
0    One  Three  a
1    One      6  b
2      2  Three  c
3  Three      8  d
4      4      9  e

In [57]:
df=pd.read_csv("/content/log.csv")
df

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN
20  1469974754     sue  advanced.html                 30    NaN     NaN
21  1469974824     sue  advanced.html                 31    NaN     NaN
22  1469974854     sue  advanced.html                 32    NaN     NaN
23  1469974924     sue  advanced.html                 33    NaN     NaN
24  1469977424     bob     intro.html                  1   True    10.0
25  1469977454     bob     intro.html                  1    NaN     NaN
26  1469977484     bob     intro.html                  1    NaN     NaN
27  1469977634     bob     intro.html                  1    NaN     NaN
28  1469977664     bob     intro.html                  1    NaN     NaN
29  1469974634  cheryl     intro.html                 12    NaN     NaN
30  1469974664  cheryl     intro.html                 13    NaN     NaN
31  1469977694     bob     intro.html                  1    NaN     NaN
32  1469977724     bob     intro.html                  1    NaN     NaN

In [58]:
df.replace(to_replace=".*.html$",value="webpage",regex=True)

          time    user    video  playback position paused  volume
0   1469974424  cheryl  webpage                  5  False    10.0
1   1469974454  cheryl  webpage                  6    NaN     NaN
2   1469974544  cheryl  webpage                  9    NaN     NaN
3   1469974574  cheryl  webpage                 10    NaN     NaN
4   1469977514     bob  webpage                  1    NaN     NaN
5   1469977544     bob  webpage                  1    NaN     NaN
6   1469977574     bob  webpage                  1    NaN     NaN
7   1469977604     bob  webpage                  1    NaN     NaN
8   1469974604  cheryl  webpage                 11    NaN     NaN
9   1469974694  cheryl  webpage                 14    NaN     NaN
10  1469974724  cheryl  webpage                 15    NaN     NaN
11  1469974454     sue  webpage                 24    NaN     NaN
12  1469974524     sue  webpage                 25    NaN     NaN
13  1469974424     sue  webpage                 23  False    10.0
14  1469974554     sue  webpage                 26    NaN     NaN
15  1469974624     sue  webpage                 27    NaN     NaN
16  1469974654     sue  webpage                 28    NaN     5.0
17  1469974724     sue  webpage                 29    NaN     NaN
18  1469974484  cheryl  webpage                  7    NaN     NaN
19  1469974514  cheryl  webpage                  8    NaN     NaN
20  1469974754     sue  webpage                 30    NaN     NaN
21  1469974824     sue  webpage                 31    NaN     NaN
22  1469974854     sue  webpage                 32    NaN     NaN
23  1469974924     sue  webpage                 33    NaN     NaN
24  1469977424     bob  webpage                  1   True    10.0
25  1469977454     bob  webpage                  1    NaN     NaN
26  1469977484     bob  webpage                  1    NaN     NaN
27  1469977634     bob  webpage                  1    NaN     NaN
28  1469977664     bob  webpage                  1    NaN     NaN
29  1469974634  cheryl  webpage                 12    NaN     NaN
30  1469974664  cheryl  webpage                 13    NaN     NaN
31  1469977694     bob  webpage                  1    NaN     NaN
32  1469977724     bob  webpage                  1    NaN     NaN

###**f. Manipulation**

In [59]:
dfs=pd.read_html("https://en.wikipedia.org/wiki/College_admissions_in_the_United_States")
len(dfs)

11